In [33]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from scipy import linalg

In [22]:
student_data = {'student': ['Abraham', 'Bobby', 'Czer', 'Doe', 'Elyra'], 
                'Math': [90, 90, 60, 60, 30],
                'Phy': [60, 90, 60, 60, 30],
                'Art': [90, 30, 60, 90, 30]}
df = pd.DataFrame(data=student_data)

In [23]:
df

student  Math  Phy  Art
0  Abraham    90   60   90
1    Bobby    90   90   30
2     Czer    60   60   60
3      Doe    60   60   90
4    Elyra    30   30   30

In [24]:
M = df[df.columns[1:]].values

In [25]:
print(M)

[[90 60 90]
 [90 90 30]
 [60 60 60]
 [60 60 90]
 [30 30 30]]


In [26]:
bar_M = np.mean(M, axis=0)

In [27]:
print(bar_M)

[66. 60. 60.]


In [41]:
coM = pd.DataFrame.cov(df)

In [42]:
print(coM)

       Math    Phy    Art
Math  630.0  450.0  225.0
Phy   450.0  450.0    0.0
Art   225.0    0.0  900.0


In [48]:
coM_ = coM.values

In [50]:
eigenValue, eigenVector = linalg.eig(coM_)

In [53]:
eigenValue.real

array([  56.02457535, 1137.5874413 ,  786.38798335])

In [52]:
eigenVector

array([[ 0.6487899 , -0.65580225, -0.3859988 ],
       [-0.74104991, -0.4291978 , -0.51636642],
       [-0.17296443, -0.62105769,  0.7644414 ]])

In [57]:
v1 = eigenVector[:, 1].reshape(3, 1)

In [58]:
v2 = eigenVector[:, 2].reshape(3, 1)

In [61]:
v2

array([[-0.3859988 ],
       [-0.51636642],
       [ 0.7644414 ]])

In [62]:
W = eigenVector[:, 1:]

In [63]:
W

array([[-0.65580225, -0.3859988 ],
       [-0.4291978 , -0.51636642],
       [-0.62105769,  0.7644414 ]])